apiVersion: v1
kind: Service
metadata:
  name: api-app-service
  labels:
    app: api-app
spec:
  selector:
    app: api-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer